# action.yml
name: 'Hugo Asciidoctor Action'
description: 'Action to generate static website using hugo by supporting AsciiDoc format'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'  
  color: 'blue'